### ISSUE TITLE
'&' symbol changing highlighting

### ISSUE THREAD

**Issue by AymDev** [v3ss0n/steam-pirate-syntax#6]
Hi,
I have a form with a $_GET action, it contains the '&' symbol (in the url) which is changing a huge part of the HTML to yellow. I don't know if there is a solution but I think it may cause problems in the readablity of the code.

```
<form action="bo.php?page=infos&action=modif_infos" method="post">
<!-- everything in HTML after & is yellow -->
```

Btw thanks for your syntax and UI which I use and enjoy everyday :)

**Comment by v3ss0n** [comment]
thanks a lot , i am a bit busy , i will look into it on weekend
